config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :rizqs
  get 'signup'  => 'users#new'
  post 'signup' => 'users#create'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get 'about'  => 'rizqs#about'
  get 'ourteam'  => 'rizqs#ourteam'
  get 'contactus'  => 'rizqs#contactus'
  get 'faqs'  => 'rizqs#faqs'
  
  resources :users
  
  get "users/:id/activate" => "users#activate", :as => "active_user"
  get "users/:id/reject" => "users#reject", :as => "reject_user"
  root 'rizqs#index'

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    # has_many :rizqs
    validates :username,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 5 }
    validates :firstname, presence: true
    validates :lastname, presence: true
    
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, :except => [:new, :create]
  before_action :correct_user, :except => [:new, :create]
   def show
    @user = User.find(params[:id])
    @lol = ""
    if @user.designation == "manager"
      if params[:post] != nil 
        if params[:post][:status] != ""
        @status = Post.new(:user_id=>@user.id,:status=>params[:post][:status])
      if @status.save
        @lol = "Updated" 
      else
        @lol = "Something went wrong"
      end
        else
          @lol = "Empty Status"
        end
      end
      if params[:usern]!= nil
        @riz = Rizq.find(params[:rizq_id])
        @nam = User.find(params[:usern][:useri])
        @nam = @nam[:username]
        @riz.volunteer = @nam
        @riz.save
      end
      if params[:delete]!= nil
        @riz = Rizq.destroy(params[:rizq_id])
      end
    end
    if params[:complete]!= nil
      @riz = Rizq.find(params[:rizq_id])
      @riz.completed = true
      @riz.save
    end
    
    @all_statuses = Post.where(:user_id=>@user.id)
    @all_pending_volunteers = User.where(:designation=>'volunteer', :approval=>false)
    @don_rizqs = Rizq.where(:action=>'Donate')
    @don_names = getArr(@don_rizqs)
    @req_rizqs = Rizq.where(:action=>'Request', :completed=>true)
    @req_names = getArr(@req_rizqs)
    @ass_req_rizqs = Rizq.where(:action=>'Request', :completed=> false, :volunteer=>nil)
    @ass_req_names = getArr(@ass_req_rizqs)
    @in_req_rizqs = Rizq.where(:action=>'Request', :completed=>false).where.not(:volunteer=>nil)
    @in_req_names = getArr(@in_req_rizqs)
    
    @voli = User.where(:designation=>'volunteer', :approval=>true)
    @voli = @voli.pluck(:username,:id)
    @myjobs = Rizq.where(:volunteer=>@user.username, :completed=>false)
    @myjobs_names = getArr(@myjobs)
    @comp_myjobs = Rizq.where(:volunteer=>@user.username, :completed=>true)
    @comp_myjobs_names = getArr(@comp_myjobs)
    

    @myreqs = Rizq.where(:user_id=>@user.id, :completed=>false)
    
    @comp_myreqs = Rizq.where(:user_id=>@user.id, :completed=>true)
    @mydons = Rizq.where(:user_id=>@user.id)
   end
  
  
  def getArr(temp)
    @temp1 = Array.new
    temp.each do |ri|
      @temp1.push(User.where(:id=>ri.user_id).pluck(:username))
    end
    return @temp1
  end
  

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome!"
      redirect_to @user
    else
      render 'new'
    end
  end
  def activate
    @voli = User.find(params[:volid])
    @voli.update_attribute(:approval, true)
    @user = User.find(session[:user_id]);
    redirect_to user_path(@user)
  end
  def reject
    @voli = User.find(params[:volid])
    @voli.destroy
    @user = User.find(session[:user_id]);
    redirect_to user_path(@user)
  end
  
  def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :cnic, :age, :address, :organization, :designation, :firstname, :lastname, :phone)
  end
  
  def user_update_params
      params.require(:user).permit(:email, :password, :password_confirmation, :cnic, :age, :address, :organization, :firstname, :lastname, :phone)
  end
    
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_update_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<h1>Update your Profile</h1>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header"></div>
    <button class="navbar-toggle" data-target="#myNavbar" data-toggle="collapse" type="button">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <img alt="RizqLogo" class="img-rounded logo" height="50px" src="http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png" width="50px"/>
        </li>
        <li>
          <%= link_to 'Edit Profile', "#" %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>
  </div>
</nav>

<br><br>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
                  
      <%= f.label :firstname %>
      <%= f.text_field :firstname, class: 'form-control' %>
      <br>
      <%= f.label :lastname %>
      <%= f.text_field :lastname, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <br>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.label :cnic %>
      <%= f.text_field :cnic, class: 'form-control' %>
      <br>  
      <%= f.label :age%>
      <%= f.text_field :age, class: 'form-control' %>
      <br>      
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      <br>      
      <%= f.label :organization %>
      <%= f.text_field :organization, class: 'form-control' %>
      <br>
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>
      <br>
      <%= f.submit "Save changes", class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header"></div>
    <button class="navbar-toggle" data-target="#myNavbar" data-toggle="collapse" type="button">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <img alt="RizqLogo" class="img-rounded logo" height="50px" src="http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png" width="50px"/>
        </li>
        <li>
          <%= link_to 'Sign Up', "#" %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>
  </div>
</nav>

<br><br>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
                  
      <%= f.label :firstname %>
      <%= f.text_field :firstname, class: 'form-control' %>
      <br>
      <%= f.label :lastname %>
      <%= f.text_field :lastname, class: 'form-control' %>
      <br>
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
      <br>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <br>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.label :cnic %>
      <%= f.text_field :cnic, class: 'form-control' %>
      <br>  
      <%= f.label :age%>
      <%= f.text_field :age, class: 'form-control' %>
      <br>      
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      <br>      
      <%= f.label :organization %>
      <%= f.text_field :organization, class: 'form-control' %>
      <br>
      <%= f.label :designation %>
      <%= f.select(:designation, options_for_select([["manager", "manager"], ["volunteer", "volunteer"], ["donor", "donor"], ["user", "user"]]), {}, { :class => 'form-control' }) %>
      <br>
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
    %div.container
        %div.navbar-header
        %button.navbar-toggle{'data-target' => '#myNavbar', 'data-toggle' => 'collapse', :type => 'button'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %div.collapse.navbar-collapse#myNavbar
            %ul.nav.navbar-nav.navbar-left
                %li
                    %img.img-rounded.logo{:alt => 'RizqLogo', :height => "50px", :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png", :width => "50px"}
                %li
                    = link_to @user.username, "#"
            %ul.nav.navbar-nav.navbar-right
                %li
                    = link_to 'Logout', logout_path
                %li
                    = link_to 'Home Page', root_url
                %li 
                    = link_to "Settings", edit_user_path(@user)


%h1= @user.username
= @lol

// = link_to "Settings", edit_user_path(@user)
- if @user.designation == "manager"
    #man.jumbotron.text-center
        = form_tag user_path(@user), :method => :get do
            %h3= label :manager, :post, 'Message'
            #mess= text_field :post, "status", :class => 'form-control', :style => "width:600px"
            %br
            = submit_tag 'post', :class => "btn btn-warning"
    
    
    #messages.container-fluid
        %h3
            = "Messages"
        %ul
        - @all_statuses.each do |status|
            %br
            %li 
                = @user.username + ": "
                = status.status            
    %br
    #volunteer.container-fluid
        %h3
            = "Approve Volunteers"
        - @all_pending_volunteers.each do |vol|
            %br
            = vol.username
            = vol.email
            = vol.cnic
            = vol.age
            = vol.address
            = vol.organization
            = vol.firstname
            = vol.lastname
            = vol.phone
            = link_to 'approve', active_user_path(:volid=>vol.id)
            = link_to 'reject', reject_user_path(:volid=>vol.id)

    %br
    #donations.container-fluid
        %h3= 'Donations!'
        - @don_rizqs.zip(@don_names).each do |rizq, uname|
            %br
            = rizq.user_id
            = uname[0]
            = rizq.food
            = rizq.quantity
            = rizq.address
            = rizq.area
            = rizq.date
            = rizq.time
            = rizq.perishable
    %br
    #completed.container-fluid
        %h3= 'Completed Requests!'
        - @req_rizqs.zip(@req_names).each do |rizq, uname|
            %br
            = rizq.user_id
            = uname[0]
            = rizq.food
            = rizq.quantity
            = rizq.address
            = rizq.area
            = rizq.date
            = rizq.time
            = rizq.perishable
    
    %br
    #assign.container-fluid
        %h3= 'Assign Volunteers!'
        - @ass_req_rizqs.zip(@ass_req_names).each do |rizq, uname|
            %br
            = rizq.user_id
            = uname[0]
            = rizq.food
            = rizq.quantity
            = rizq.address
            = rizq.area
            = rizq.date
            = rizq.time
            = rizq.perishable
            = form_tag user_path(@user), :method => :get do
                = hidden_field_tag "rizq_id", rizq.id
                = select(:usern,:useri, @voli)
                = submit_tag 'assign', :class => "btn btn-warning"
            = form_tag user_path(@user), :method => :get do
                = hidden_field_tag "delete", "delete"
                = hidden_field_tag "rizq_id", rizq.id
                = submit_tag 'delete', :class => "btn btn-warning"
    %br
    #progress.container-fluid
        %h3= 'In Progress!'
        - @in_req_rizqs.zip(@in_req_names).each do |rizq, uname|
            %br
            = rizq.user_id
            = uname[0]
            = rizq.food
            = rizq.quantity
            = rizq.address
            = rizq.area
            = rizq.date
            = rizq.time
            = rizq.perishable
            = rizq.volunteer
            = form_tag user_path(@user), :method => :get do
                = hidden_field_tag "rizq_id", rizq.id
                = select(:usern,:useri, @voli)
                = submit_tag 'change', :class => "btn btn-warning"
            = form_tag user_path(@user), :method => :get do
                = hidden_field_tag "delete", "delete"
                = hidden_field_tag "rizq_id", rizq.id
                = submit_tag 'delete', :class => "btn btn-warning"
        
- if @user.designation == "volunteer" && @user.approval == false
    -5.times do
        %br
    %h2.text-center= "Approval Pending"
- elsif @user.designation == "volunteer"
    %br
    #ajobs.container-fluid
        %h3= "Assigned Jobs"
    - @myjobs.zip(@myjobs_names).each do |rizq, uname|
        %br
        = uname[0]
        = rizq.food
        = rizq.quantity
        = rizq.address
        = rizq.area
        = rizq.date
        = rizq.time
        = rizq.perishable
        = form_tag user_path(@user), :method => :get do
            = hidden_field_tag "complete", "complete"
            = hidden_field_tag "rizq_id", rizq.id
            = submit_tag 'complete', :class => "btn btn-warning"
    %br
    #cjobs.container-fluid
        %h3= "Completed Jobs"
    - @comp_myjobs.zip(@comp_myjobs_names).each do |rizq, uname|
        %br
        = uname[0]
        = rizq.food
        = rizq.quantity
        = rizq.address
        = rizq.area
        = rizq.date
        = rizq.time
        = rizq.perishable
        
- if @user.designation == "user"
    %br
    #mreq.container-fluid
        %h3= "My requests"
    - @myreqs.each do |rizq|
        %br
        = rizq.food
        = rizq.quantity
        = rizq.address
        = rizq.area
        = rizq.date
        = rizq.time
        = rizq.perishable
        = rizq.volunteer
        = form_tag user_path(@user), :method => :get do
            = hidden_field_tag "delete", "delete"
            = hidden_field_tag "rizq_id", rizq.id
            = submit_tag 'delete', :class => "btn btn-warning"
    %br
    #creq.container-fluid
        %h3= "Completed Requests"
    - @comp_myreqs.each do |rizq|
        %br
        = rizq.food
        = rizq.quantity
        = rizq.address
        = rizq.area
        = rizq.date
        = rizq.time
        = rizq.perishable
        = rizq.volunteer
        
- if @user.designation == "donor"
    %br
    #donor.container-fluid
        %h3= "My Donations"
    - @mydons.each do |rizq|
        %br
        = rizq.food
        = rizq.quantity
        = rizq.address
        = rizq.area
        = rizq.date
        = rizq.time
        = rizq.perishable