config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :rizqs
  get 'signup'  => 'users#new'
  post 'signup' => 'users#create'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get 'about'  => 'rizqs#about'
  get 'ourteam'  => 'rizqs#ourteam'
  get 'contactus'  => 'rizqs#contactus'
  get 'faqs'  => 'rizqs#faqs'
  
  resources :users
  
  get "users/:id/activate" => "users#activate", :as => "active_user"
  get "users/:id/reject" => "users#reject", :as => "reject_user"
  root 'rizqs#index'

end

app/models/rizq.rb
class Rizq < ActiveRecord::Base
end

app/controllers/rizqs_controller.rb
class RizqsController < ApplicationController
  before_action :set_rizq, only: [:show, :edit, :update, :destroy]

  # GET /rizqs
  # GET /rizqs.json
  def index
    @rizqs = Rizq.all
    
    @managerposts = Post.where(:user_id=>User.where(:designation=>"manager").uniq.pluck(:id)).order(created_at: :desc).limit(5)
    # @statuses = Array.new
    @names = Array.new
    @imgnames = Array.new
    ii = 0
    @managerposts.each do |poe|
      # @statuses.push(poe)
      @names.push(User.where(:id=>poe.user_id).pluck(:username))
      @imgnames.push("bg1.jpg")
      @imgnames[-1][2] = (@imgnames[-1][2].to_i + ii).to_s
      ii = ii + 1
      @usid = session[:user_id]
    @temp = "Donate Food"
    if User.where(:id=>@usid).pluck(:designation)[0] == "user"
      @temp = "Request Food"
    end
    end
    # @statuses = @statuses.zip(@names)
    # if logged_in?
    #   @user = User.find(params[:id])
    # end
  end
  def about
  end
  def faqs
  end
  def contactus
  end
  def ourteam
  end

  # GET /rizqs/1
  # GET /rizqs/1.json
  def show
  end

  # GET /rizqs/new
  def new
    @rizq = Rizq.new
    @usid = session[:user_id]
    @add = User.where(:id=>@usid).pluck(:address)[0]
    @temp1 = "Donate"
    if User.where(:id=>@usid).pluck(:designation)[0] == "user"
      @temp1 = "Request"
    end
  end

  # GET /rizqs/1/edit
  def edit
  end

  # POST /rizqs
  # POST /rizqs.json
  def create
    if (session[:user_id] != nil)
    @rizq = Rizq.new(rizq_params)

    respond_to do |format|
      if @rizq.save
        format.html { redirect_to @rizq, notice: 'Rizq was successfully created.' }
        format.json { render :show, status: :created, location: @rizq }
      else
        format.html { render :new }
        format.json { render json: @rizq.errors, status: :unprocessable_entity }
      end
    end
    else
      respond_to do |format|
      format.html { redirect_to root_url, notice: 'Please log in.'}
      end
    end
  end

  # PATCH/PUT /rizqs/1
  # PATCH/PUT /rizqs/1.json
  def update
    respond_to do |format|
      if @rizq.update(rizq_params)
        format.html { redirect_to @rizq, notice: 'Rizq was successfully updated.' }
        format.json { render :show, status: :ok, location: @rizq }
      else
        format.html { render :edit }
        format.json { render json: @rizq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rizqs/1
  # DELETE /rizqs/1.json
  def destroy
    @rizq.destroy
    respond_to do |format|
      format.html { redirect_to rizqs_url, notice: 'Rizq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rizq
      @rizq = Rizq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rizq_params
      params.require(:rizq).permit(:user_id, :action, :food, :quantity, :address, :area, :date, :time, :perishable)
    end
end

app/helpers/rizqs_helper.rb
module RizqsHelper
end

app/views/rizqs/_form.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header"></div>
      <button class="navbar-toggle" data-target="#myNavbar" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-left">
          <li>
            <img alt="RizqLogo" class="img-rounded logo" height="50px" src="http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png" width="50px"/>
          </li>
          <li>
            <%= link_to 'Donate Food', "#" %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        </ul>
      </div>
    </div>
  </nav>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@rizq) do |f| %>
      <% if @rizq.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@rizq.errors.count, "error") %> prohibited this rizq from being saved:</h2>
    
          <ul>
          <% @rizq.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      
      
  
    <br><br>
    
      <div class="field">
        <%= f.label :UserID %><br>
        <%= f.text_field :user_id, :value => @usid , class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.hidden_field :action, :value => @temp1 %>
      </div>
      <br>
      <div class="field">
        <%= f.label :food %><br>
        <%= f.text_field :food, class: 'form-control' %>
        <!--<%= f.text_area :food %>-->
      </div>
      <br>
      <div class="field">
        <%= f.label :quantity %> (In terms of number persons that can be fed) <br>
        <%= f.text_field :quantity, class: 'form-control' %>
        <!--<%= f.text_field :quantity %>-->
      </div>
      <br>
      <div class="field">
        <%= f.label :address %><br>
        <%= f.text_field :address, :value => @add , class: 'form-control' %>
        <!--<%= f.text_area(:address, :value => @add) %>-->
      </div>
      <br>
      <div class="field">
        <%= f.label :area %><br>
        <%= f.text_field :area, class: 'form-control' %>
        <!--<%= f.text_field :area %>-->
      </div>
      <br>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.date_select :date, class: 'form-control' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :time %> (Approximate time of pickup)  <br>
        <%= f.time_select :time, class: 'form-control' %>
      </div>
      <br>
      <div class="field">
        <%= f.check_box :perishable, class: 'checkbox-inline' %>
        <%= f.label :perishable %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit :Submit , class: "btn btn-warning"%>
      </div>
    <% end %>
  </div>
</div>

app/views/rizqs/about.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
    %div.container
        %div.navbar-header
        %button.navbar-toggle{'data-target' => '#myNavbar', 'data-toggle' => 'collapse', :type => 'button'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %div.collapse.navbar-collapse#myNavbar
            %ul.nav.navbar-nav.navbar-left
                %li
                    %img.img-rounded.logo{:alt => 'RizqLogo', :height => "50px", :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png", :width => "50px"}
                %li
                    = link_to 'About', "#"
            %ul.nav.navbar-nav.navbar-right
                %li
                    = link_to 'Home Page', root_url
                    
// %div.container-fluid.bg-grey.text-center
//     %p This is some text.
//     %p This is another text.
    
%div.container
    %h1 Hello World!
    .row
        #one.col-sm-6
            %img#about{:alt => "About", :src => "about.jpg"}
        #two.col-sm-6
            // %h8 About
            %p 
            We are a group of people from 
            %b Lahore University of Management Sciences 
            %b (LUMS), 
            who want to play their part in ridding Pakistan of the nuisances of hunger and malnutrition. 
            We intend to do this in the following ways:
            %ol
                %li
                    By eliminating food wastage in our society by collecting surplus food from functions and providing it to needy.
                %li
                    By promoting awareness regarding healthy dietary habits
                %li
                    By creating a transparent food distribution channel by which people can directly donate food, both freshly made and leftover/surplus from events, and indirectly through monetary donations.
            
            So if you want to donate or have any surplus food from any sort of function (Weddings, Dawats, Home-dinner Parties, Pre-Wedding Ceremonies etc), just call us, we will collect it from your doorstep and deliver it to the needy people.
            %br
            %br
                %b Let's Share Rizq
            %br
                %b Let's SHARE FOOD. FEED HAPPINESS.

app/views/rizqs/contactus.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
    %div.container
        %div.navbar-header
        %button.navbar-toggle{'data-target' => '#myNavbar', 'data-toggle' => 'collapse', :type => 'button'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %div.collapse.navbar-collapse#myNavbar
            %ul.nav.navbar-nav.navbar-left
                %li
                    %img.img-rounded.logo{:alt => 'RizqLogo', :height => "50px", :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png", :width => "50px"}
                %li
                    = link_to 'Contact Us', "#"
            %ul.nav.navbar-nav.navbar-right
                %li
                    = link_to 'Home Page', root_url
                    
%div.container
    %h1 Hello World!
    .row
        #oneCU.col-sm-6
            %img#contactUs{:alt => "Contact Us", :src => "contactUs2.jpg"}
        #twoCU.col-sm-6
            %b#phoneTitle Phone
            %ul#contactNum
                // %li#num
                //     0322-88242089
                %li#num
                    0321-7967979
                %li#num
                    0321-8406523
            %br
            %br
            %br
            %br
            %b#emailTitle Email
            %ul#emailAdd
                %li#email
                    rizq.sharefood@gmail.com

app/views/rizqs/edit.html.erb
<h1>Editing Rizq</h1>

<%= render 'form' %>

<%= link_to 'Show', @rizq %> |
<%= link_to 'Back', rizqs_path %>

app/views/rizqs/faqs.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
    %div.container
        %div.navbar-header
        %button.navbar-toggle{'data-target' => '#myNavbar', 'data-toggle' => 'collapse', :type => 'button'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %div.collapse.navbar-collapse#myNavbar
            %ul.nav.navbar-nav.navbar-left
                %li
                    %img.img-rounded.logo{:alt => 'RizqLogo', :height => "50px", :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png", :width => "50px"}
                %li
                    = link_to 'FAQs', "#"
            %ul.nav.navbar-nav.navbar-right
                %li
                    = link_to 'Home Page', root_url
                    
%div.container-fluid
    .row
        #three.col-sm-6.col-md-offset-3
            // %img#faq1{:alt => "FAQs", :src => "faq1.jpg"}        #three.col-sm-6
            %h3.text-center Q: What Kind of food we collect?
            %p.text-center We accept any kind of food, we just need to know details concerning food type, like if its raw or cooked, packaged, hot or cold, and how much there is. In essence we have only one criteria for the food that can be donated: "Any food that you, yourself would eat is donatable.
            
           

app/views/rizqs/index.html.haml
%nav.navbar.navbar-default.navbar-fixed-bottom.bg-1
    %div.container
        %div.navbar-header
        %button.navbar-toggle{'data-target' => '#myNavbar', 'data-toggle' => 'collapse', :type => 'button'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %div.collapse.navbar-collapse#myNavbarbottom
            %ul.nav.navbar-nav.navbar-right
                %li
                    = link_to 'About', about_path
                %li
                    = link_to 'Our Team', ourteam_path
                %li
                    = link_to 'FAQs', faqs_path
                %li
                    = link_to 'Contact us', contactus_path
                
%nav.navbar.navbar-default.navbar-fixed-top
    %div.container
        %div.navbar-header
        %button.navbar-toggle{'data-target' => '#myNavbar', 'data-toggle' => 'collapse', :type => 'button'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %div.collapse.navbar-collapse#myNavbar
            %ul.nav.navbar-nav.navbar-left
                %li
                    %img.img-rounded.logo{:alt => 'RizqLogo', :height => "50px", :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png", :width => "50px"}
            %ul.nav.navbar-nav.navbar-right
                %li 
                    - if logged_in?
                        = link_to 'Profile', user_path(current_user)
                    // - else
                    //     = link_to 'Login', login_path
                %li
                    - if logged_in?
                        = link_to @temp, new_rizq_path
                    // - else
                    //     = link_to 'Login', login_path
                %li
                    - if logged_in?
                        = link_to 'Logout', logout_path
                    - else
                        = link_to 'Login', login_path
                        

// %div.container-fluid.bg-grey.text-center
//     %img.img-rounded.logo{:alt => 'RizqLogo', :height => "300px", :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png", :width => "300px", :align => "middle"}

- 5.times do
    %br
// - @managerposts.zip(@names).each do |status, uname|
//     %br
//     %li
//         = uname[0] + ': '
//         = status.status

#myCarousel.carousel.slide{"data-ride" => "carousel"}
    %ol.carousel-indicators
        %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
        %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
        %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
        %li{"data-slide-to" => "3", "data-target" => "#myCarousel"}
        %li{"data-slide-to" => "4", "data-target" => "#myCarousel"}
        %li{"data-slide-to" => "5", "data-target" => "#myCarousel"}
    .carousel-inner{:role => "listbox"}
        .item.active
            %img#logo{:alt => 'RizqLogo', :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo%20medium_zps9c6ofeu8.png"}
                .carousel-caption
                    // %h3 Rizq
                    // %p Welcome to Rizq
        - @managerposts.zip(@names).zip(@imgnames).each do |zippo, img|
            .item
                %img{:alt => img, :src => img}
                    .carousel-caption
                        %h3 
                            = zippo[1][0] + ': '
                        %p 
                            = zippo[0].status
    %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
        %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
        %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel", :role => "button"}
        %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
        %span.sr-only Next
        
// #myCarousel.carousel.slide{"data-ride" => "carousel"}
//     %ol.carousel-indicators
//         %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
//         %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
//         %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
//     .carousel-inner{:role => "listbox"}
//         // - @managerposts.zip(@names).each do |status, uname|
//         .item
//             .carousel-caption
//                 %h3
//                     Hello
//                     Bye
//                     // = uname[0] + ': '
//                     // = status.status
//         // .item
//         //     %img.img-rounded.logo{:alt => 'RizqLogo', :height => "300px", :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/allpagebg_zpsjjcremcy.png", :width => "300px", :align => "middle"}
//         //     .carousel-caption
//         //         %h3 Chicago
//         //         %p Thank you, Chicago - A night we won't forget.
//         // .item
//         //     %img.img-rounded.logo{:alt => 'RizqLogo', :height => "300px", :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/allpagebg_zpsjjcremcy.png", :width => "300px", :align => "middle"}
//         //     .carousel-caption
//         //         %h3 LA
//         //         %p Even though the traffic was a mess, we had the best time.
//     %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
//         %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
//         %span.sr-only Previous
//     %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel", :role => "button"}
//         %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
//         %span.sr-only Next

app/views/rizqs/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', rizqs_path %>

app/views/rizqs/ourteam.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
    %div.container
        %div.navbar-header
        %button.navbar-toggle{'data-target' => '#myNavbar', 'data-toggle' => 'collapse', :type => 'button'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %div.collapse.navbar-collapse#myNavbar
            %ul.nav.navbar-nav.navbar-left
                %li
                    %img.img-rounded.logo{:alt => 'RizqLogo', :height => "50px", :src => "http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png", :width => "50px"}
                %li
                    = link_to 'Our Team', "#"
            %ul.nav.navbar-nav.navbar-right
                %li
                    = link_to 'Home Page', root_url
%div.container#contOT
    // %h1 Hello World!
    .row
        #oneOT.col-sm-6.col-md-offset-3
            %p.text-center Huzaifa Ahmad CEO & Co-Founder 
            %p.text-center Musa Aamir COO & Co-Founder
            %p.text-center Qasim Javaid Khan CMO & Co-Founder

app/views/rizqs/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header"></div>
    <button class="navbar-toggle" data-target="#myNavbar" data-toggle="collapse" type="button">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <img alt="RizqLogo" class="img-rounded logo" height="50px" src="http://i1118.photobucket.com/albums/k606/apocalypse8/rizq%20logo_zpspsfuuoad.png" width="50px"/>
        </li>
        <li>
          <%= link_to 'Receipt', "#" %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>
  </div>
</nav>
<br><br><br><br><br><br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @rizq.action %>
</p>

<p>
  <strong>Food:</strong>
  <%= @rizq.food %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @rizq.quantity %>
</p>

<p>
  <strong>Address:</strong>
  <%= @rizq.address %>
</p>

<p>
  <strong>Area:</strong>
  <%= @rizq.area %>
</p>

<p>
  <strong>Date:</strong>
  <%= @rizq.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @rizq.time %>
</p>

<p>
  <strong>Perishable:</strong>
  <%= @rizq.perishable %>
</p>

<%= link_to 'Back', rizqs_path %>